# Supervised Learning Model Evaluation Lab

Complete the exercises below to solidify your knowledge and understanding of supervised learning model evaluation.

In [128]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

## Regression Model Evaluation

In [129]:
column_names = ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'MEDV']
data = pd.read_csv('housing.csv', header=None, delimiter=r"\s+", names=column_names)

In [130]:
"""
CRIM - per capita crime rate by town
ZN - proportion of residential land zoned for lots over 25,000 sq.ft.
INDUS - proportion of non-retail business acres per town.
CHAS - Charles River dummy variable (1 if tract bounds river; 0 otherwise)
NOX - nitric oxides concentration (parts per 10 million)
RM - average number of rooms per dwelling
AGE - proportion of owner-occupied units built prior to 1940
DIS - weighted distances to five Boston employment centres
RAD - index of accessibility to radial highways
TAX - full-value property-tax rate per $10,000
PTRATIO - pupil-teacher ratio by town
B - 1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town
LSTAT - % lower status of the population
MEDV - Median value of owner-occupied homes in $1000's"""

"\nCRIM - per capita crime rate by town\nZN - proportion of residential land zoned for lots over 25,000 sq.ft.\nINDUS - proportion of non-retail business acres per town.\nCHAS - Charles River dummy variable (1 if tract bounds river; 0 otherwise)\nNOX - nitric oxides concentration (parts per 10 million)\nRM - average number of rooms per dwelling\nAGE - proportion of owner-occupied units built prior to 1940\nDIS - weighted distances to five Boston employment centres\nRAD - index of accessibility to radial highways\nTAX - full-value property-tax rate per $10,000\nPTRATIO - pupil-teacher ratio by town\nB - 1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town\nLSTAT - % lower status of the population\nMEDV - Median value of owner-occupied homes in $1000's"

In [131]:
data

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0   
1    0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2    0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   
3    0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0   
4    0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93     0  0.573  6.593  69.1  2.4786    1  273.0   
502  0.04527   0.0  11.93     0  0.573  6.120  76.7  2.2875    1  273.0   
503  0.06076   0.0  11.93     0  0.573  6.976  91.0  2.1675    1  273.0   
504  0.10959   0.0  11.93     0  0.573  6.794  89.3  2.3889    1  273.0   
505  0.04741   0.0  11.93     0  0.573  6.030  80.8  2.5050    1  273.0   

     PTRATIO       B  LSTAT  MEDV  
0       15.3  396.90   4.98  24.0  
1       17.8  396.90   9.14  21.6  
2       17.8  392.83   4.03  34.7  
3       18.7  394.63   2.94  33.4  
4       18.7  396.90   5.33  36.2  
..       ...     ...    ...   ...  
501     21.0  391.99   9.67  22.4  
502     21.0  396.90   9.08  20.6  
503     21.0  396.90   5.64  23.9  
504     21.0  393.45   6.48  22.0  
505     21.0  396.90   7.88  11.9  

[506 rows x 14 columns]

## 1. Split this data set into training (80%) and testing (20%) sets.

The `MEDV` field represents the median value of owner-occupied homes (in $1000's) and is the target variable that we will want to predict.

In [132]:
# Your code here :
X = data.drop(["MEDV"], axis=1)
y = data["MEDV"]

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.2)

print("Train: ", X_train.shape,  y_train.shape)
print("Test: ", X_test.shape,y_test.shape)

Train:  (404, 13) (404,)
Test:  (102, 13) (102,)


## 2. Train a `LinearRegression` model on this data set and generate predictions on both the training and the testing set.

In [133]:
# Your code here :
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train, y_train)

print(model.intercept_, model.coef_)

y_train_pred = model.predict(X_train)
y_test_pred = model.predict(X_test)

37.376747333637724 [-1.13877387e-01  5.14747584e-02  3.71637570e-02  2.97757442e+00
 -1.97177160e+01  3.89301737e+00 -7.65341055e-04 -1.65814905e+00
  3.32627729e-01 -1.33513977e-02 -9.37942491e-01  8.98424213e-03
 -5.21201478e-01]


## 3. Calculate and print R-squared for both the training and the testing set.

In [134]:
# Your code here :
from sklearn.metrics import r2_score
print("R² Train: ", r2_score(y_train, y_train_pred))
print("R² Test: ", r2_score(y_test, y_test_pred))

R² Train:  0.7438918148048067
R² Test:  0.7197322030074778


## 4. Calculate and print mean squared error for both the training and the testing set.

In [135]:
# Your code here :
from sklearn.metrics import mean_squared_error
print("MSE Train: ", mean_squared_error(y_train_pred, y_train))
print("MSE Test: ", mean_squared_error(y_test_pred, y_test))

MSE Train:  21.563641667071046
MSE Test:  23.7477092157332


## 5. Calculate and print mean absolute error for both the training and the testing set.

In [136]:
# Your code here :
from sklearn.metrics import mean_absolute_error
print("MAE Train: ", mean_absolute_error(y_train_pred, y_train))
print("MAE Test: ", mean_absolute_error(y_test_pred, y_test))

MAE Train:  3.243385874928183
MAE Test:  3.4944667532766296


## Classification Model Evaluation

In [137]:
from sklearn.datasets import load_iris
data = load_iris()

In [138]:
print(data.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive attributes and the class
:Attribute Information:
    - sepal length in cm
    - sepal width in cm
    - petal length in cm
    - petal width in cm
    - class:
            - Iris-Setosa
            - Iris-Versicolour
            - Iris-Virginica

:Summary Statistics:

============== ==== ==== ======= ===== ====================
                Min  Max   Mean    SD   Class Correlation
============== ==== ==== ======= ===== ====================
sepal length:   4.3  7.9   5.84   0.83    0.7826
sepal width:    2.0  4.4   3.05   0.43   -0.4194
petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
============== ==== ==== ======= ===== ====================

:Missing Attribute Values: None
:Class Distribution: 33.3% for each of 3 classes.
:Cr

In [139]:
column_names = data.feature_names

In [140]:
df = pd.DataFrame(data['data'],columns=column_names)

In [141]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [142]:
target = pd.DataFrame(data.target)

In [143]:
data.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [144]:
data['target_names']

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

## 6. Split this data set into training (80%) and testing (20%) sets.

The `class` field represents the type of flower and is the target variable that we will want to predict.

In [145]:
# Your code here :
X = df
y = data.target
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.2)

## 7. Train a `LogisticRegression` model on this data set and generate predictions on both the training and the testing set.

In [155]:
# Your code here :
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train, y_train)

y_train_pred = model.predict(X_train)
y_test_pred = model.predict(X_test)

## 8. Calculate and print the accuracy score for both the training and the testing set.

In [156]:
# Your code here :
from sklearn.metrics import accuracy_score
print("Accuracy Train: ", accuracy_score(y_train, y_train_pred))
print("Accuracy Test: ", accuracy_score(y_test, y_test_pred))

Accuracy Train:  0.975
Accuracy Test:  1.0


## 9. Calculate and print the balanced accuracy score for both the training and the testing set.

In [148]:
# Your code here :
from sklearn.metrics import balanced_accuracy_score
print("Balanced Accuracy Train: ", balanced_accuracy_score(y_train, y_train_pred))
print("Balanced Accuracy Test: ", balanced_accuracy_score(y_test, y_test_pred))

Balanced Accuracy Train:  0.9729729729729729
Balanced Accuracy Test:  1.0


## 10. Calculate and print the precision score for both the training and the testing set.

In [149]:
# Your code here :
from sklearn.metrics import precision_score
print("Precision Score Train: ", precision_score(y_train, y_train_pred, average='weighted'))
print("Precision Score Test: ", precision_score(y_test, y_test_pred, average='weighted'))

Precision Score Train:  0.9765957446808511
Precision Score Test:  1.0


## 11. Calculate and print the recall score for both the training and the testing set.

In [150]:
# Your code here :
from sklearn.metrics import recall_score
print("Recall Score Train: ", recall_score(y_train, y_train_pred, average='weighted'))
print("Recall Score Test: ", recall_score(y_test, y_test_pred, average='weighted'))

Recall Score Train:  0.975
Recall Score Test:  1.0


## 12. Calculate and print the F1 score for both the training and the testing set.

In [151]:
# Your code here :
from sklearn.metrics import f1_score
print("F1 Score Score Train: ", f1_score(y_train, y_train_pred, average='weighted'))
print("F1 Score Score Test: ", f1_score(y_test, y_test_pred, average='weighted'))

F1 Score Score Train:  0.9748839188980033
F1 Score Score Test:  1.0


## 13. Generate confusion matrices for both the training and the testing set.

In [152]:
# Your code here :
from sklearn.metrics import classification_report, confusion_matrix
cm_train = confusion_matrix(y_train, y_train_pred)
print("Train Confusion Matrix:\n", cm_train)

cm_test = confusion_matrix(y_test, y_test_pred)
print("\nTest Confusion Matrix:\n", cm_test)

Train Confusion Matrix:
 [[39  0  0]
 [ 0 34  3]
 [ 0  0 44]]

Test Confusion Matrix:
 [[11  0  0]
 [ 0 13  0]
 [ 0  0  6]]


## Bonus: For each of the data sets in this lab, try training with some of the other models you have learned about, recalculate the evaluation metrics, and compare to determine which models perform best on each data set.

In [164]:
# Have fun here !
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
import xgboost as xgb
import numpy as np

def compare_models(X_train, X_test, y_train, y_test, regression = True):
    models = {}
    if regression:
        models["Linear Regression"]  = LinearRegression()
    else: # Classification
        models["Logistic Regression"] = LogisticRegression()
        models["KNN"] =  KNeighborsClassifier()
        models["Decision Tree"] =  DecisionTreeClassifier()
        models["Random Forest"] =   RandomForestClassifier()
        models["SVM"] =  SVC()
        models["XGBoost"] =  xgb.XGBClassifier(use_label_encoder=False, eval_metric='logloss')


    for name, model in models.items():
        model.fit(X_train, y_train)
        y_train_pred = model.predict(X_train)
        y_test_pred = model.predict(X_test)

        print(f"\n{name}:\n")
        print("R²               \t Train: ", r2_score(y_train, y_train_pred), "\t | Test: ", r2_score(y_test, y_test_pred))
        print("MSE              \t Train: ", mean_squared_error(y_train, y_train_pred), "\t | Test: ", mean_squared_error(y_test, y_test_pred))
        print("MAE              \t Train: ", mean_absolute_error(y_train, y_train_pred), "\t | Test: ", mean_absolute_error(y_test, y_test_pred))
        if regression:
            pass
        else: # Classification            
            print("Accuracy         \t Train: ", accuracy_score(y_train, y_train_pred), "\t | Test: ", accuracy_score(y_test, y_test_pred))
            print("Balanced Accuracy\t Train: ", balanced_accuracy_score(y_train, y_train_pred), "\t | Test: ", balanced_accuracy_score(y_test, y_test_pred))
            print("Precision        \t Train: ", precision_score(y_train, y_train_pred, average='weighted'), "\t | Test: ", precision_score(y_test, y_test_pred, average='weighted'))
            print("Recall           \t Train: ", recall_score(y_train, y_train_pred, average='weighted'), "\t | Test: ", recall_score(y_test, y_test_pred, average='weighted'))
            print("Precision        \t Train: ", f1_score(y_train, y_train_pred, average='weighted'), "\t | Test: ", f1_score(y_test, y_test_pred, average='weighted'))


# Second Model (Data already loaded)
print("== Iris DataSet: == ")
compare_models(X_train, X_test, y_train, y_test, regression = False)

# Decision Tree, Random Forest and XGBoost seems to perfectly predict the dependant feature in this categorical problem

== Iris DataSet: == 

Logistic Regression:

R²               	 Train:  0.9637644690488173 	 | Test:  1.0
MSE              	 Train:  0.025 	 | Test:  0.0
MAE              	 Train:  0.025 	 | Test:  0.0
Accuracy         	 Train:  0.975 	 | Test:  1.0
Balanced Accuracy	 Train:  0.9729729729729729 	 | Test:  1.0
Precision        	 Train:  0.9765957446808511 	 | Test:  1.0
Recall           	 Train:  0.975 	 | Test:  1.0
Precision        	 Train:  0.9748839188980033 	 | Test:  1.0

KNN:

R²               	 Train:  0.9396074484146956 	 | Test:  1.0
MSE              	 Train:  0.041666666666666664 	 | Test:  0.0
MAE              	 Train:  0.041666666666666664 	 | Test:  0.0
Accuracy         	 Train:  0.9583333333333334 	 | Test:  1.0
Balanced Accuracy	 Train:  0.9578214578214578 	 | Test:  1.0
Precision        	 Train:  0.958425925925926 	 | Test:  1.0
Recall           	 Train:  0.9583333333333334 	 | Test:  1.0
Precision        	 Train:  0.9582820276024832 	 | Test:  1.0

Decision Tree:

R²   

In [166]:
# First Model
print("\n\n== Housin DataSet: == ")
column_names = ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'MEDV']
data2 = pd.read_csv('housing.csv', header=None, delimiter=r"\s+", names=column_names)
X2 = data2.drop(["MEDV"], axis=1)
# y2 = data2["MEDV"]

X_train2, X_test2, y_train2, y_test2 = train_test_split(X2, y2, test_size=.2)

compare_models(X_train2, X_test2, y_train2, y_test2, regression = True)

# The models we have seen until now are for categorical problems, at this moment the only one I can use for regression is the Linear Model



== Housin DataSet: == 

Linear Regression:

R²               	 Train:  0.7202607674273944 	 | Test:  0.8026359334744073
MSE              	 Train:  23.144524366030495 	 | Test:  17.89199449193511
MAE              	 Train:  3.391776421979769 	 | Test:  3.0553403689776157
